# Generated by infobeans-qai.ps1
VENV_DIR      := venv
WHEEL_NAME    := infobeans_qai-0.1.0b3-py3-none-any.whl
APP_NAME      := appname
GIT_REMOTE    := https://github.com/<org>/<repo>.git
XRAY_CLIENT_ID     := <XRAY_CLIENT_ID>
XRAY_CLIENT_SECRET := <XRAY_CLIENT_SECRET>
XRAY_API_BASE_URL  := https://xray.cloud.getxray.app
XRAY_PROJECT_KEY   := <XRAY_PROJECT_KEY>
XRAY_PROJECT_ID    := <XRAY_PROJECT_ID>
JIRA_URL           := <JIRA_URL>
JIRA_API_EMAIL     := <JIRA_API_EMAIL>
JIRA_API_TOKEN     := <JIRA_API_TOKEN>
